// Action Types
export const FETCH_APPOINTMENTS = 'FETCH_APPOINTMENTS';
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';

export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const ADD_PATIENT = 'ADD_PATIENT';
export const UPDATE_PATIENT = 'UPDATE_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';

export const FETCH_DOCTORS = 'FETCH_DOCTORS';
export const ADD_DOCTOR = 'ADD_DOCTOR';
export const UPDATE_DOCTOR = 'UPDATE_DOCTOR';
export const DELETE_DOCTOR = 'DELETE_DOCTOR';

export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_SELECTED_CONTACT = 'SET_SELECTED_CONTACT';

export const FETCH_ROOMS = 'FETCH_ROOMS';
export const ADD_ROOM = 'ADD_ROOM';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const DELETE_ROOM = 'DELETE_ROOM';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR'; 