export const DOCTOR_TYPES = {
  FETCH_DOCTORS: 'FETCH_DOCTORS',
  ADD_DOCTOR: 'ADD_DOCTOR',
  UPDATE_DOCTOR: 'UPDATE_DOCTOR',
  DELETE_DOCTOR: 'DELETE_DOCTOR',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR'
}; 